"""add triage context to chat sessions

Revision ID: 0007_add_triage_context_to_chat_sessions
Revises: 0006_fix_volunteer_id_nullable
Create Date: 2024-12-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007_add_triage_context_to_chat_sessions'
down_revision = '0006_fix_volunteer_id_nullable'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar colunas nullable primeiro
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triage_triggered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('triage_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('triage_declined_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('triage_context', sa.Text(), nullable=True))

    # Atualizar valores NULL para FALSE
    op.execute("UPDATE chat_sessions SET triage_triggered = FALSE WHERE triage_triggered IS NULL")
    
    # Tornar a coluna NOT NULL após definir os valores
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('triage_triggered', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_column('triage_context')
        batch_op.drop_column('triage_declined_reason') 
        batch_op.drop_column('triage_status')
        batch_op.drop_column('triage_triggered')

    # ### end Alembic commands ###