"""Initial migration

Revision ID: 7b312a1dd25e
Revises: fec4fa3d6b59
Create Date: 2025-08-31 16:25:03.368624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b312a1dd25e'
down_revision = 'fec4fa3d6b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_session_created'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_session_type'), table_name='chat_messages')
    op.alter_column('chat_sessions', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_chat_sessions_last_activity'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_status_last_activity'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_user_status'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_uuid'), table_name='chat_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_chat_sessions_uuid'), 'chat_sessions', ['uuid'], unique=False)
    op.create_index(op.f('idx_chat_sessions_user_status'), 'chat_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_chat_sessions_status_last_activity'), 'chat_sessions', ['status', 'last_activity'], unique=False)
    op.create_index(op.f('idx_chat_sessions_last_activity'), 'chat_sessions', ['last_activity'], unique=False)
    op.alter_column('chat_sessions', 'last_activity',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('idx_chat_messages_session_type'), 'chat_messages', ['session_id', 'message_type'], unique=False)
    op.create_index(op.f('idx_chat_messages_session_created'), 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###
