"""add last_activity to chat_session

Revision ID: 0dd5225f0638
Revises: be4016995e9b
Create Date: 2025-08-12 18:57:42.357807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd5225f0638'
down_revision = 'be4016995e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'last_activity')
    # ### end Alembic commands ###
