"""add uuid to ChatSession

Revision ID: 76c81b486abc
Revises: 329b0164f58f
Create Date: 2025-08-12 15:16:09.149132

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '76c81b486abc'
down_revision = '329b0164f58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Adiciona a coluna como nullable
    op.add_column('chat_sessions', sa.Column('uuid', sa.String(length=36), nullable=True, unique=True))
    # 2. Preenche os valores para registros existentes
    conn = op.get_bind()
    chat_sessions = conn.execute(sa.text("SELECT id FROM chat_sessions WHERE uuid IS NULL"))
    for row in chat_sessions:
        conn.execute(
            sa.text("UPDATE chat_sessions SET uuid = :uuid WHERE id = :id"),
            {"uuid": str(uuid.uuid4()), "id": row.id}
        )
    # 3. Altera para NOT NULL
    op.alter_column('chat_sessions', 'uuid', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'uuid')
    # ### end Alembic commands ###
